# Generated by Django 5.2 on 2025-04-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeOrder',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=20)),
                ('model_no', models.CharField(max_length=50)),
                ('bike_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
